export const ADD_BUNS = 'ADD_BUNS';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const ALL_ITEMS_CONSTRUCTOR = 'ALL_ITEMS_CONSTRUCTOR';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';