export const GET_DATA = 'GET_DATA';
export const GET_CONSTRUCTOR_INGREDIENTS = 'GET_INGREDIENTS';
export const GET_DETAILS = 'ADD_DETAILS';
export const DELETE_DETAILS = 'DELETE_DETAILS';
export const GET_ORDERS = 'GET_ORDERS';